config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('pymentorat.urls')),
    path('administrationdusite/', admin.site.urls),
]

mentorat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('mgt/', admin.site.urls),
    path('', include('pymentorat.urls')),
]

pymentorat/urls.py
from django.urls import path, include
from django_filters.views import FilterView

from . import views
from .models import Contract

app_name='pymentorat'

urlpatterns = [
    # Login page
    path(
        'accounts/',
        include('django.contrib.auth.urls')
    ),
    # Home page
    path(
        '',
        views.index,
        name='index'
    ),
    # Student's pages
    path(
        'student/',
        views.student_filter_list,
        name='student_list'
    ),
    path(
        'student/<int:id_student>/',
        views.student_details,
        name='student_details'
    ),
    path(
        'student_update/<int:id_student>/',
        views.student_update,
        name='student_update'
    ),
    # Teacher's pages
    path(
        'teacher/',
        views.teacher_filter_list,
        name='teacher_list'
    ),
    path(
        'teacher_update/<int:id_teacher>/',
        views.teacher_update,
        name='teacher_update'
    ),
    # Mentor's pages
    path(
        'mentors/',
        views.mentor_filter_list,
        name='mentor_list'
    ),
    path(
        'mentor/<int:id_mentor>/',
        views.mentor_details,
        name='mentor_details'
    ),
    path(
        'mentor_create/',
        views.mentor_create,
        name='mentor_create'
    ),
    path(
        'mentor_create/<int:id_student>/',
        views.mentor_create_from_student,
        name='mentor_create_from_student'
    ),
    path(
        'mentor_update/<int:id_mentor>/',
        views.mentor_update,
        name='mentor_update')
    ,
    # EDA's pages
    path(
        'eda/',
        views.eda_filter_list,
        name='eda_list'
    ),
    path(
        'eda_nomentor/',
        views.eda_filter_nomentor_list,
        name='eda_nomentor_list'
    ),
    path(
        'eda/<int:id_eda>/',
        views.eda_details,
        name='eda_details'
    ),
    path(
        'eda_create/',
        views.eda_create,
        name='eda_create'
    ),
    path(
        'eda_create/<int:id_student>/',
        views.eda_create_from_student,
        name='eda_create_from_student'
    ),
    path(
        'eda_update/<int:id_eda>/',
        views.eda_update,
        name='eda_update'
    ),
    # Contract's pages
    path(
        'contract/',
        views.contract_filter_list,
        name='contract_list'
    ),
    path(
        'contract_create/<int:id_eda>/',
        views.contract_create_from_eda,
        name='contract_create'
    ),
    path(
        'contract_duplicate/<int:id_contract>/',
        views.contract_duplicate,
        name='contract_duplicate'
    ),
    path(
        'contract_update/<int:id_contract>/',
        views.contract_update,
        name='contract_update'
    ),
    path(
        'contract_list/',
        views.SimpleContractListView.as_view(),
        name='contract_simple_list'
    ),
    path(
        'contract_print/<int:id_contract>/',
        views.contract_pdf,
        name='contract_pdf'
    ),
    # Convocation's pages
    path(
        'convocation_create/<int:id_contract>/',
        views.convocation_create_from_contract,
        name='convocation_create'
    ),
    path(
        'convocation_update/<int:id_convocation>/',
        views.convocation_update,
        name='convocation_update'
    ),
    path(
        'convocation_delete/<int:id_convocation>/',
        views.convocation_delete,
        name='convocation_delete'
    ),
    path(
        'convocation_print/<int:id_convocation>/',
        views.convocation_pdf,
        name='convocation_pdf'
    ),
    # Stats pages
    path(
        'statistiques/',
        views.statistiques,
        name='statistiques'
    )
    # For Class Based Views
    # path(
    #     'contrat/',
    #     view=FilterView.as_view(model=Contract),
    #     name='contract_list'
    # ),
    # path(
    #     'contrat_create/',
    #     view=views.ContractCreateView.as_view(),
    #     name='contract_list'
    # ),
]

pymentorat/views.py
from datetime import date

from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.utils.timezone import now
from django.utils.text import slugify

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFont
from io import BytesIO

from .models import Discipline, Student, Teacher, EDA, Mentor, Contract, Convocation
from .forms import MentorForm, EDAForm, StudentForm, TeacherForm, ContractForm, ParagraphErrorList, ContractFormWithEDA
from .forms import MentorFormWithStudent, EDAFormWithStudent, ConvocationFormWithContract, ContractFormDuplicate
from .apps import CURRENT_YEAR
from .filter import MentorFilter, EDAFilter, StudentFilter, TeacherFilter, ContractFilter

@login_required
def index(request):
    """ Function based view to render the home page """
    disciplines = Discipline.objects.order_by('name')
    mentors = Mentor.objects.filter(year=CURRENT_YEAR, is_active=True)
    edas = EDA.objects.filter(year=CURRENT_YEAR, is_active=True)
    contracts = Contract.objects.filter(year=CURRENT_YEAR, end_date=None).order_by('discipline')
    convocations = Convocation.objects.filter(date__gt = now()).order_by('date', 'time')
    context = {
        'disciplines': disciplines,
        'mentors': mentors,
        'nb_mentors': mentors.count(),
        'edas': edas,
        'nb_edas': edas.count(),
        'contracts': contracts,
        'nb_contracts': contracts.count(),
        'convocations': convocations,
        'nbconvocations': convocations.count(),
    }
    return render(request, 'pymentorat/index.html', context)


# Views for students
@login_required
def student_filter_list(request):
    """ Function based view to render the list of all the students, with a filter. """
    student_list = Student.objects.order_by('name')
    student_filter = StudentFilter(request.GET, queryset=student_list)
    return render(request, 'pymentorat/student_list.html', {'filter': student_filter})

@login_required
def student_details(request, id_student):
    """ Function based view to edit an EDA. """
    student = get_object_or_404(Student, pk=id_student)
    contract_list = Contract.objects.filter(Q(mentor__student=student) | Q(eda__student=student), year=CURRENT_YEAR)
    mentor_list = Mentor.objects.filter(student=student, year=CURRENT_YEAR)
    eda_list = EDA.objects.filter(student=student, year=CURRENT_YEAR)
    context = {
        'student_pk' : student.pk,
        'student_name': student.name,
        'student_vorname': student.vorname,
        'student_portable' : student.portable,
        'student_email': student.email,
        'classe': student.classe,
        'contracts': contract_list,
        'nb_contracts': contract_list.count(),
        'mentors' : mentor_list,
        'nb_mentors': mentor_list.count(),
        'edas' : eda_list,
        'nb_edas': eda_list.count(),
    }

    return render(request,'pymentorat/student_details.html', context)

@login_required
def student_update(request, id_student):
    """ Function based view to edit a students. """
    student = get_object_or_404(Student, pk=id_student)
    form = StudentForm(request.POST or None, instance=student)
    context = {
        'student_name': student.name,
        'student_vorname' : student.vorname,
        'student_id' : student.id_OD,
        'student_classe' : student.classe
    }
    if form.is_valid():
        form.save()
        return redirect(student.get_absolute_url())
    context['form'] = form
    return render(request,'pymentorat/student_form.html', context)


# Views for teachers
@login_required
def teacher_filter_list(request):
    """ Function based view to render the list of all the teachers, with a filter. """
    teacher_list = Teacher.objects.order_by('name')
    teacher_filter = TeacherFilter(request.GET, queryset=teacher_list)
    return render(request, 'pymentorat/teacher_list.html', {'filter': teacher_filter})


@login_required
def teacher_update(request, id_teacher):
    """ Function based view to edit a teacher. """
    teacher = get_object_or_404(Teacher, pk=id_teacher)
    form = TeacherForm(request.POST or None, instance=teacher)
    if form.is_valid():
        form.save()
        return redirect('pymentorat:teacher_list')
    return render(request,'pymentorat/teacher_form.html',{'form':form})


# Views for mentors
@login_required
def mentor_filter_list(request):
    """ Function based view to render the list of current year mentors, with a filter. """
    mentor_list = Mentor.objects.filter(year=CURRENT_YEAR, is_active=True).order_by('student__name')
    mentor_filter = MentorFilter(request.GET, queryset=mentor_list)
    return render(request, 'pymentorat/mentor_list.html', {'filter': mentor_filter})

@login_required
def mentor_details(request, id_mentor):
    """ Function based view to edit an EDA. """
    mentor = get_object_or_404(Mentor, pk=id_mentor)
    contract_list = Contract.objects.filter(mentor=mentor, year=CURRENT_YEAR)
    context = {
        'mentor_pk' : mentor.pk,
        'mentor_name': mentor.student.name,
        'mentor_vorname': mentor.student.vorname,
        'mentor_portable' : mentor.student.portable,
        'mentor_classe': mentor.student.classe,
        'mentor_discipline' : mentor.discipline,
        'student_pk' : mentor.student.pk,
        'teacher_name': mentor.teacher.name,
        'teacher_vorname': mentor.teacher.vorname,
        'contracts': contract_list,
        'nb_contracts': contract_list.count()
    }

    return render(request,'pymentorat/mentor_details.html', context)

@login_required
def mentor_create(request):
    """ Function based view to create a mentor. """
    if request.POST:
        form = MentorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pymentorat:mentor_list')
    else:
        form = MentorForm()
    return render(request, 'pymentorat/mentor_form.html', {'form':form})


@login_required
def mentor_create_from_student(request, id_student):
    """ Function based view to create a mentor from a selected student. """
    student = get_object_or_404(Student, pk=id_student)

    form = MentorFormWithStudent(request.POST or None, error_class=ParagraphErrorList,
                                 initial={'student': student})
    context = {
        'student_name': student.name,
        'student_vorname': student.vorname,
        'student_classe': student.classe,
        'status': 'new',
    }
    if form.is_valid():
        form.save()
        return redirect('pymentorat:mentor_list')
    context['form'] = form
    return render(request,'pymentorat/mentor_form.html', context=context)


@login_required
def mentor_update(request, id_mentor):
    """ Function based view to edit a mentor. """
    mentor = get_object_or_404(Mentor, pk=id_mentor)
    form = MentorFormWithStudent(request.POST or None, instance=mentor)
    context = {
        'student_name': mentor.student.name,
        'student_vorname': mentor.student.vorname,
        'student_classe' : mentor.student.classe,
        'status': 'update',
    }
    if form.is_valid():
        form.save()
        return redirect('pymentorat:mentor_list')
    context['form'] = form
    return render(request,'pymentorat/mentor_form.html', context=context)


# Views for EDAs
@login_required
def eda_filter_list(request):
    """ Function based view to render the list of current year EDAs, with a filter. """
    eda_list = EDA.objects.filter(year=CURRENT_YEAR, is_active=True).order_by('inscription_date')
    eda_filter = EDAFilter(request.GET, queryset=eda_list)
    context = {
        'filter': eda_filter,
        'title': "Liste des élèves demandeurs d'aide"
    }
    return render(request, 'pymentorat/eda_list.html', context)


@login_required
def eda_filter_nomentor_list(request):
    """ Function based view to render the list of current year EDAs waiting for a mentor, with a filter. """
    eda_list = EDA.objects.filter(contract__end_date=None, year=CURRENT_YEAR, is_active=True).order_by('inscription_date')
    eda_filter = EDAFilter(request.GET, queryset=eda_list)
    context = {
        'filter': eda_filter,
        'title': "EDA sans mentor"
    }
    return render(request, 'pymentorat/eda_list.html', context)

@login_required
def eda_details(request, id_eda):
    """ Function based view to edit an EDA. """
    eda = get_object_or_404(EDA, pk=id_eda)
    contract_list = Contract.objects.filter(eda=eda, year=CURRENT_YEAR)
    context = {
        'eda_pk' : eda.pk,
        'eda_name': eda.student.name,
        'eda_vorname': eda.student.vorname,
        'eda_portable' : eda.student.portable,
        'eda_classe': eda.student.classe,
        'eda_discipline' : eda.discipline,
        'student_pk': eda.student.pk,
        'teacher_name': eda.teacher.name,
        'teacher_vorname': eda.teacher.vorname,
        'contracts': contract_list,
        'nb_contracts': contract_list.count()
    }

    return render(request,'pymentorat/eda_details.html', context)

@login_required
def eda_create(request):
    """ Function based view to create an EDA. """
    if request.POST:
        form = EDAForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('pymentorat:eda_list')
    else:
        form = MentorForm()
    return render(request,'pymentorat/eda_form.html',{'form':form})


@login_required
def eda_create_from_student(request, id_student):
    """ Function based view to create a mentor from a selected student. """
    student = get_object_or_404(Student, pk=id_student)

pymentorat/templates/pymentorat/eda_details.html
{% extends 'pymentorat/base.html' %}

{% block buttons %}
        <a href="{% url 'pymentorat:eda_list' %}" class="btn btn-outline-secondary btn-sm" id="eda_list_button">
            <i class="fa fa-bars" aria-hidden="true"></i> Liste des demandeurs
        </a>
        <a href="{% url 'pymentorat:eda_update' eda_pk %}" class="btn btn-outline-secondary btn-sm" id="student_list_button">
            <i class="fas fa-marker"></i> Modifier la demande
        </a>
        <a href="{% url 'pymentorat:contract_create' eda_pk %}" class="btn btn-outline-secondary btn-sm" id="student_list_button">
            <i class="fas fa-folder-plus" title="Nouveau contrat"></i> Créer un contrat
        </a>
        <a href="{% url 'pymentorat:student_details' student_pk %}" class="btn btn-outline-secondary btn-sm" id="student_details">
            <i class="fas fa-info-circle"></i> Détails de l'élève
        </a>
{% endblock%}

{% block content %}

    <div class="container text-center">
        <h3>Demandeur d'aide</h3>
        <h5> Elève : <a href="{% url 'pymentorat:student_details' eda_pk %}">{{eda_vorname}} {{eda_name}} ({{eda_classe}})</a></h5>
        <h5> Branche : {{eda_discipline}}</h5>
        <p>Maître de branche : {{teacher_vorname}} {{teacher_name}}</p>
        <p>Remarque :</p>
        <p>{{remark}}</p>

    </div>

{% if contracts %}
        <h3>Liste des contrats ({{ nb_contracts }}) :</h3>
        <table class="table table-striped table-hover">
            <tr>
                <th>EDA</th>
                <th>Mentor</th>
                <th>Discipline</th>
                <th>Date de début</th>
                <th>Date de fin</th>
                <th>Actions</th>
            </tr>
            {% for contract in contracts %}
            <tr>
                <td>
                    {{contract.eda.student}}
                </td>
                <td>
                    {{contract.mentor.student}} ({{contract.mentor.student.classe}})
                    <a href="{% url 'pymentorat:mentor_details' contract.mentor.pk %}" >
                        <i class="fas fa-info-circle" title="Ouvrir détails du mentor"></i>
                    </a>
                </td>
                <td>
                    {{contract.discipline}}
                </td>
                <td>
                    {{contract.begin_date | date:" d F Y"}}
                </td>
                 <td>
                    {{contract.end_date | date:"d F Y"}}
                </td>
                <td>
                    <a href="{% url 'pymentorat:contract_update' contract.pk %}">
                        <i class="fas fa-marker" title="Modifier le contrat"></i>
                    </a>

                    <a href="{% url 'pymentorat:contract_pdf' contract.pk %}">
                        <i class="fas fa-print" title="Imprimer le contrat"></i>
                    </a>

                    <a href="{% url 'pymentorat:convocation_create' contract.pk %}">
                        <i class="far fa-calendar-plus" title="Créer une convocation"></i>
                    </a>
                    <a href="{% url 'pymentorat:contract_duplicate' contract.pk %}">
                        <i class="fas fa-folder-plus" title="Dupliquer le contrat"></i>
                    </a>
                </td>

            </tr>
            {% endfor %}
        </table>
    {% else %}
        Aucun contrat trouvé pour .
    {% endif %}
{% endblock%}

pymentorat/templates/pymentorat/index.html
{% extends 'pymentorat/base.html' %}


    {% block buttons %}

    <a href="{% url 'pymentorat:student_list' %}" class="btn btn-outline-secondary btn-sm" id="student_list_button">
            <i class="fa fa-bars" aria-hidden="true"></i> Liste des élèves
    </a>
    <a href="{% url 'pymentorat:mentor_list' %}" class="btn btn-outline-secondary btn-sm" id="mentor_list_button">
            <i class="fa fa-bars" aria-hidden="true"></i> Liste des mentors
            <span class="badge badge-pill badge-primary" title="Nb. contrats">
                {{nb_mentors}}
            </span>
    </a>
    <a href="{% url 'pymentorat:eda_list' %}" class="btn btn-outline-secondary btn-sm" id="eda_list_button">
            <i class="fa fa-bars" aria-hidden="true"></i> Liste des demandeurs
            <span class="badge badge-pill badge-primary" title="Nb. contrats">
                {{nb_edas}}
            </span>
    </a>
    <a href="{% url 'pymentorat:contract_list' %}" class="btn btn-outline-secondary btn-sm" id="contract_list_button">
            <i class="fa fa-bars" aria-hidden="true"></i> Liste des contrats
            <span class="badge badge-pill badge-primary" title="Nb. contrats">
                {{nb_contracts}}
            </span>
    </a>
    {% endblock%}

    {% block content %}

    <h3>Prochains rendez-vous</h3>

    <table class="table table-striped table-hover">
        <tr>
            <th>
                Demandeur
            </th>
            <th>
                Mentor
            </th>
            <th>
                Date
            </th>
            <th>
                Lieu
            </th>
            <th>
                Actions
            </th>
        </tr>
    {% for convocation in convocations %}
        <tr>
            <td>
                {{convocation.contract.eda.student.name}}
                {{convocation.contract.eda.student.vorname}}
                ({{convocation.contract.eda.student.classe}})
            </td>
            <td>
                {{convocation.contract.mentor.student.name}}
                {{convocation.contract.mentor.student.vorname}}
                ({{convocation.contract.mentor.student.classe}})
            </td>
            <td>
                {{convocation.date}} à
                {{convocation.time}}
            </td>
            <td>
                {{convocation.place}}
            </td>
            <td>
                <a href="{% url 'pymentorat:convocation_update' convocation.pk %}">
                    <i class="fas fa-marker" title="Modifier la convocation"></i>
                </a>

                <a href="{% url 'pymentorat:convocation_pdf' convocation.pk %}">
                    <i class="fas fa-print" title="Réimprimer la convocation"></i>
                </a>
                <a href="{% url 'pymentorat:convocation_delete' convocation.pk %}">
                    <i class="fas fa-times-circle" title="Supprimer la convocation"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
    </table>

    <br>

    <h3>Contrats en cours</h3>
    <table class="table table-striped table-hover">
        <tr>
            <th>
                Demandeur
            </th>
            <th>
                Mentor
            </th>
            <th>
                Discipline
            </th>
            <th>
                Date de début
            </th>
            <th>
                Actions
            </th>
        </tr>
    {% for contract in contracts %}
        <tr>
            <td>
                {{contract.eda.student.name}}
                {{contract.eda.student.vorname}}
                ({{contract.eda.student.classe}})
            </td>
            <td>
                {{contract.mentor.student.name}}
                {{contract.mentor.student.vorname}}
                ({{contract.mentor.student.classe}})
            </td>
            <td>
                {{contract.discipline}}
            </td>
            <td>
                {{contract.begin_date}}
            </td>
            <td>
                <a href="{% url 'pymentorat:contract_update' contract.pk %}">
                    <i class="fas fa-marker" title="Modifier le contrat"></i>
                </a>

                <a href="{% url 'pymentorat:contract_pdf' contract.pk %}">
                    <i class="fas fa-print" title="Imprimer le contrat"></i>
                </a>

                <a href="{% url 'pymentorat:convocation_create' contract.pk %}">
                    <i class="far fa-calendar-plus" title="Créer une convocation"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
    </table>

<!--    <h3>Listes des mentors</h3>

    <table>
    {% for mentor in mentors %}
    <tr>
        <td>
            {{mentor.student.nom}}
        </td>
        <td>
            {{mentor.student.vorname}}
        </td>
        <td>
            {{mentor.discipline}}
        </td>

    </tr>
    {% endfor %}
    </table>

    <h3>Listes des élèves demandeurs d'aide</h3>

    <table>
    {% for eda in edas %}
    <tr>
        <td>
            {{eda.student.name}}
        </td>
        <td>
            {{eda.student.vorname}}
        </td>
        <td>
            {{eda.discipline}}
        </td>

    </tr>
    {% endfor %}
    </table>-->

    {% endblock %}

pymentorat/templates/pymentorat/student_details.html
{% extends 'pymentorat/base.html' %}

{% block buttons %}
        <a href="{% url 'pymentorat:student_list' %}" class="btn btn-outline-secondary btn-sm" id="student_list_button">
            <i class="fa fa-bars" aria-hidden="true"></i> Liste des élèves
        </a>
        <a href="{% url 'pymentorat:student_update' student_pk %}" class="btn btn-outline-secondary btn-sm" id="student_update_button">
            <i class="fas fa-marker"></i> Modifier l'élève
        </a>
        <a href="{% url 'pymentorat:mentor_create_from_student' student_pk %}" class="btn btn-outline-secondary btn-sm" id="student_create_mentor_button">
            <i class="fas fa-plus-circle"></i> Inscrire comme mentor
        </a>
        <a href="{% url 'pymentorat:eda_create_from_student' student_pk %}" class="btn btn-outline-secondary btn-sm" id="student_create_eda_button">
            <i class="fas fa-plus-square" ></i> Inscrire comme EDA
        </a>
{% endblock%}



{% block content %}
    <div class="container text-center">
        <h3>Elève : {{student_vorname}} {{student_name}}</h3>
        <p>Classe actuelle : {{classe}}</p>
        <p>Email : {{student_email}}</p>
        <p>Portable : {{student_portable}}</p>
        <p>Téléphone : {{student_tel}}</p>
    </div>

        <br><hr>

    <h4>Demandes d'aide ({{ nb_edas }}):</h4>

    {% if edas %}

        <table class="table table-striped table-hover">
            <tr>
                <th>Demandeur</th>
                <th>Discipline</th>
                <th>Classe</th>
                <th>Maître</th>
                <th>Date d'inscription</th>
                <th>Actions</th>
            </tr>
            {% for eda in edas %}
            <tr>
                <td>
                    {{eda.student.name}} {{eda.student.vorname}}
                </td>
                <td>
                    {{eda.discipline}}
                </td>
                <td>
                    {{eda.student.classe}}
                </td>
                 <td>
                    {{eda.teacher}}
                </td>
                <td>
                    {{eda.inscription_date | date:"d F Y"}}
                </td>
                <td>
                    <a href="{% url 'pymentorat:eda_update' eda.pk %}">
                        <i class="fas fa-marker" title="Modifier la demande d'aide"></i>
                    </a>

                    <a href="{% url 'pymentorat:contract_create' eda.pk %}">
                        <i class="far fa-folder-plus" title="Nouveau contrat"></i>
                    </a>
                </td>

            </tr>
            {% endfor %}
        </table>
    {% else %}
        Aucune demande d'aide trouvée.
    {% endif %}

    <br><hr>

    <h4>Inscriptions comme mentor ({{ nb_mentors }}):</h4>

    {% if mentors %}
        <table class="table table-striped table-hover">
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Discipline</th>
                <th>Classe</th>
                <th>Maître</th>
                <th>Année</th>
                <th>Nb contrats</th>
                <th>Actions</th>
            </tr>
            {% for mentor in mentors %}
            <tr>
                <td>
                    {{mentor.student.name}}
                </td>
                <td>
                    {{mentor.student.vorname}}
                </td>
                <td>
                    {{mentor.discipline}}
                </td>
                <td>
                    {{mentor.student.classe}}
                </td>
                 <td>
                    {{mentor.teacher}}
                </td>
                <td>
                    {{mentor.year}}
                </td>
                <td>
                    <a href="{% url 'pymentorat:mentor_details' mentor.pk %}">
                        <span class="badge badge-pill badge-primary" title="Nb. contrats">
                            {{mentor.get_nb_contracts}}
                        </span>
                    </a>
                </td>
                <td>
                    <a href="{% url 'pymentorat:mentor_update' mentor.pk %}">
                        <i class="fas fa-marker" title="Modifier le mentor"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        Aucune inscription comme mentor trouvée.
    {% endif %}

    <br><hr>

    <h4>Contrats ({{ nb_contracts }}):</h4>

    {% if contracts %}

        <table class="table table-striped table-hover">
            <tr>
                <th>EDA</th>
                <th>Mentor</th>
                <th>Discipline</th>
                <th>Date de début</th>
                <th>Date de fin</th>
                <th>Actions</th>
            </tr>
            {% for contract in contracts %}
            <tr>
                <td>
                    {{contract.eda.student}} ({{contract.eda.student.classe}})
                    <a href="{% url 'pymentorat:eda_details' contract.eda.pk %}">
                        <i class="fas fa-info-circle" title="Ouvrir détails du demandeur"></i>
                    </a>
                </td>
                <td>
                    {{contract.mentor.student}} ({{contract.mentor.student.classe}})
                    <a href="{% url 'pymentorat:mentor_details' contract.mentor.pk %}">
                        <i class="fas fa-info-circle" title="Ouvrir détails du mentor"></i>
                    </a>
                </td>
                <td>
                    {{contract.discipline}}
                </td>
                <td>
                    {{contract.begin_date | date:" d F Y"}}
                </td>
                 <td>
                    {{contract.end_date | date:"d F Y"}}
                </td>
                <td>
                    <a href="{% url 'pymentorat:contract_update' contract.pk %}">
                        <i class="fas fa-marker" title="Modifier le contrat"></i>
                    </a>

                    <a href="{% url 'pymentorat:contract_pdf' contract.pk %}">
                        <i class="fas fa-print" title="Imprimer le contrat"></i>
                    </a>

                    <a href="{% url 'pymentorat:convocation_create' contract.pk %}">
                        <i class="far fa-calendar-plus" title="Créer une convocation"></i>
                    </a>
                </td>

            </tr>
            {% endfor %}
        </table>
    {% else %}
        Aucun contrat trouvé.
    {% endif %}



{% endblock%}

pymentorat/templates/pymentorat/student_list.html
{% extends 'pymentorat/base.html' %}

{% block buttons %}

{% endblock%}

{% block content %}
    <h3>Listes des élèves</h3>

    <div class="container text-center">
    <form class="form-inline" method="get">
        {{ filter.form.as_p }}
        <button type="submit">Filtrer</button>
    </form>
    </div>

    {% if filter.qs %}
        <table class="table table-striped table-hover">
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Classe</th>
                <th>Email</th>
                <th>Portable</th>
                <th>Actions</th>
            </tr>
            {% for student in filter.qs %}
            <tr>
                <td>
                    {{student.name}}
                </td>
                <td>
                    {{student.vorname}}
                </td>
                <td>
                    {{student.classe}}
                </td>
                <td>
                    {{student.email}}
                </td>
                 <td>
                    {{student.portable}}
                </td>
                <td>
                    <a href="{% url 'pymentorat:student_details' student.pk %}">
                        <i class="fas fa-info-circle" title="Ouvrir détails de l'élève"></i>
                    </a>

                    <a href="{% url 'pymentorat:student_update' student.pk %}">
                        <i class="fas fa-marker" title="Modifier l'élève"></i>
                    </a>

                    <a href="{% url 'pymentorat:mentor_create_from_student' student.pk %}">
                        <i class="fas fa-plus-circle" title="Inscrire nouveau mentor"></i>
                    </a>

                    <a href="{% url 'pymentorat:eda_create_from_student' student.pk %}">
                        <i class="fas fa-plus-square" title="Inscrire nouveau demandeur"></i>
                    </a>
                </td>

            </tr>
            {% endfor %}
        </table>
    {% else %}
        Aucun élève trouvé.
    {% endif %}
{% endblock%}